name: build
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            CI: true

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14

            # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows
            - uses: actions/cache@v2
              id: cache
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: install
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: check and build
              run: |
                  npm run check
                  npm run build
